/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "./src/test.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include <string.h>
#include <check.h>
#include "./http_lib/http.h"
#include "./parser_args/parser_args.h"

START_TEST(func_check_file_1)
{
ck_assert_int_eq(check_file("./src/templates/hello.html"), 0);

}
END_TEST

START_TEST(func_check_file_2)
{
ck_assert_int_eq(check_file("./Makefile"), 1);

}
END_TEST

START_TEST(func_check_file_3)
{
ck_assert_int_eq(check_file("./Makefile.html"), 2);

}
END_TEST

START_TEST(func_check_file_4)
{
ck_assert_int_eq(check_file(""), 1);

}
END_TEST

START_TEST(func_check_file_5)
{
ck_assert_int_eq(check_file(NULL), -2);

}
END_TEST

START_TEST(func_parse_response_1)
{
HTTP_answer temp = parse_response("GET teststring.html HTTP/1.1\n");
ck_assert_str_eq(temp.type, "GET");
ck_assert_str_eq(temp.file, "teststring.html");
ck_assert_str_eq(temp.proto, "HTTP/1.1");

}
END_TEST

START_TEST(func_parse_response_2)
{
HTTP_answer temp = parse_response("DELETE teststring.html\n");
ck_assert_str_eq(temp.type, "");
ck_assert_str_eq(temp.file, "");
ck_assert_str_eq(temp.proto, "");

}
END_TEST

START_TEST(func_parse_response_3)
{
HTTP_answer temp = parse_response(NULL);
ck_assert_str_eq(temp.type, "");
ck_assert_str_eq(temp.file, "");
ck_assert_str_eq(temp.proto, "");

}
END_TEST

START_TEST(func_parse_response_4)
{
HTTP_answer temp = parse_response("");
ck_assert_str_eq(temp.type, "");
ck_assert_str_eq(temp.file, "");
ck_assert_str_eq(temp.proto, "");

}
END_TEST

START_TEST(func_parse_response_5)
{
HTTP_answer temp = parse_response("DELETEDELETE teststring.html HTTP/1.1\n");
ck_assert_str_eq(temp.type, "");
ck_assert_str_eq(temp.file, "");
ck_assert_str_eq(temp.proto, "");

}
END_TEST

START_TEST(func_parse_response_6)
{
HTTP_answer temp = parse_response("POST teststring.htmlteststring.htmlteststring.html HTTP/1.1\n");
ck_assert_str_eq(temp.type, "POST");
ck_assert_str_eq(temp.file, "teststring.htmlteststring.htmlteststring.html");
ck_assert_str_eq(temp.proto, "HTTP/1.1");

}
END_TEST

START_TEST(func_parse_response_7)
{
HTTP_answer temp = parse_response("DELETE teststring HTTP/1.1HTTP/1.1HTTP/1.1\n");
ck_assert_str_eq(temp.type, "");
ck_assert_str_eq(temp.file, "");
ck_assert_str_eq(temp.proto, "");

}
END_TEST

START_TEST(func_create_answer_1)
{
char* temp = create_answer("./src/templates/test.html");
ck_assert_str_eq(temp, "HTTP/1.1 200 OK\nContent-Type: text/html\n\nHTML FOR TEST");
free(temp);

}
END_TEST

START_TEST(func_create_answer_2)
{
char* temp = create_answer(NULL);
ck_assert_ptr_eq(temp, NULL);

}
END_TEST

START_TEST(func_create_answer_3)
{
char* temp = create_answer("");
ck_assert_ptr_eq(temp, NULL);

}
END_TEST

START_TEST(func_pars_arg_1)
{
ck_assert_int_eq(is_dir_exists("."), 1);

}
END_TEST

START_TEST(func_pars_arg_2)
{
ck_assert_int_eq(is_dir_exists("./"), 1);

}
END_TEST

START_TEST(func_pars_arg_3)
{
ck_assert_int_eq(is_dir_exists("./no_exist_dir/"), 0);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, func_check_file_1);
    tcase_add_test(tc1_1, func_check_file_2);
    tcase_add_test(tc1_1, func_check_file_3);
    tcase_add_test(tc1_1, func_check_file_4);
    tcase_add_test(tc1_1, func_check_file_5);
    tcase_add_test(tc1_1, func_parse_response_1);
    tcase_add_test(tc1_1, func_parse_response_2);
    tcase_add_test(tc1_1, func_parse_response_3);
    tcase_add_test(tc1_1, func_parse_response_4);
    tcase_add_test(tc1_1, func_parse_response_5);
    tcase_add_test(tc1_1, func_parse_response_6);
    tcase_add_test(tc1_1, func_parse_response_7);
    tcase_add_test(tc1_1, func_create_answer_1);
    tcase_add_test(tc1_1, func_create_answer_2);
    tcase_add_test(tc1_1, func_create_answer_3);
    tcase_add_test(tc1_1, func_pars_arg_1);
    tcase_add_test(tc1_1, func_pars_arg_2);
    tcase_add_test(tc1_1, func_pars_arg_3);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
